# Generated by Django 5.2.4 on 2025-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_curso_examen_intentarexamen_pregunta_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_pregunta',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen de la Pregunta'),
        ),
    ]
