# Generated by Django 5.2.4 on 2025-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_pregunta_imagen_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='comprobante_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprobante de Pago'),
        ),
    ]
