# Generated by Django 5.2.4 on 2025-08-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_inscripcion_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentarexamen',
            name='preguntas_seleccionadas',
            field=models.JSONField(default=list, verbose_name='Preguntas Seleccionadas'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Pregunta Activa'),
        ),
    ]
