# Generated by Django 5.2.4 on 2025-08-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_intentarexamen_evaluador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentarexamen',
            name='resultado_practico',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name='Resultado Práctico'),
        ),
        migrations.AddField(
            model_name='intentarexamen',
            name='observaciones_practico',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Examen Práctico'),
        ),
    ]
