# Generated by Django 5.2.4 on 2025-08-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20250811_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tiene_certificado',
            field=models.BooleanField(default=False, verbose_name='Tiene Certificado'),
        ),
    ]
