# Generated by Django 5.2.4 on 2025-08-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_tiene_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tiene_certificado',
        ),
        migrations.AddField(
            model_name='intentarexamen',
            name='fecha_programada_practica',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada para Examen Práctico'),
        ),
    ]
