# Generated by Django 5.2.4 on 2025-08-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20250812_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentarexamen',
            name='duracion_programada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración Programada (minutos)'),
        ),
        migrations.AddField(
            model_name='intentarexamen',
            name='hora_programada_practica',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Programada para Examen Práctico'),
        ),
    ]
