# Generated by Django 5.2.4 on 2025-08-13 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_intentarexamen_duracion_programada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('completado', 'Completado'), ('expirado', 'Expirado')], default='programado', max_length=20, verbose_name='Estado')),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='pendiente', max_length=20, verbose_name='Resultado')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.examen', verbose_name='Examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Examen Asignado',
                'verbose_name_plural': 'Exámenes Asignados',
                'db_table': 'examenes_usuarios',
                'ordering': ['fecha_programada', 'hora_inicio'],
                'unique_together': {('usuario', 'examen')},
            },
        ),
    ]
