# Generated by Django 5.2.4 on 2025-08-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_examenusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago'),
        ),
    ]
