# Generated by Django 5.2.4 on 2025-08-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_inscripcion_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='aceptado_admin',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Aprobado por el Admin'),
        ),
    ]
