# Generated by Django 5.2.5 on 2025-08-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_inscripcion_aceptado_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_pregunta',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/', verbose_name='Imagen de la Pregunta'),
        ),
    ]
