# Generated by Django 5.2.5 on 2025-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_pregunta_imagen_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del Curso'),
        ),
    ]
